In [18]:
import numpy as np


In [19]:
arr=np.random.randint(0,10,size=(5,4))
arr

array([[4, 7, 0, 6],
       [3, 8, 7, 4],
       [5, 0, 0, 7],
       [4, 7, 7, 5],
       [2, 2, 4, 9]])

In [20]:
arr[2,-1]

np.int64(7)

In [21]:
arr[-1,-1]

np.int64(9)

In [22]:
#Slicing 2D array

In [23]:
arr[1:4,2:]

array([[7, 4],
       [0, 7],
       [7, 5]])

In [24]:
arr[:,-2:]

array([[0, 6],
       [7, 4],
       [0, 7],
       [7, 5],
       [4, 9]])

In [25]:
arr[2:4,1:-1]

array([[0, 0],
       [7, 7]])

In [ ]:
#3D array
np.random.seed(99)
arr1=np.random.randint(0,10,size=(3,4,3))
arr1

In [ ]:
#Indexing
arr1[:,:,-1]

array([[7, 9, 0, 3]])

In [45]:
arr1[: , : ,-1:]

array([[[9],
        [8],
        [5],
        [7]],

       [[1],
        [6],
        [2],
        [8]],

       [[7],
        [9],
        [0],
        [3]]])

In [ ]:
import pandas as pd