In [1]:
import numpy as np

In [3]:
arr1=np.ones((3,3))

In [5]:
arr1

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [4]:
arr2=np.array([1,2,3])

In [6]:
arr2

array([1, 2, 3])

In [7]:
np.add(arr1,arr2)

array([[2., 3., 4.],
       [2., 3., 4.],
       [2., 3., 4.]])