In [1]:
import numpy as np

In [2]:
array_2D=np.random.randint(1,9,size=(3,3))

In [3]:
array_2D

array([[4, 4, 7],
       [7, 8, 2],
       [4, 1, 7]])

Access the element in the second row, third column of the 2D array you created above.

In [11]:
array_2D[1:2,2:3]

array([[2]])

Slice the first two rows and the first two columns from the same array.

In [13]:
array_2D[:2,:2]

array([[4, 4],
       [7, 8]])

Modify the value in the last row and first column to 100.

In [20]:
array_2D[0,-1]=100

In [22]:
array_2D[0,-1]

np.int64(100)