In [1]:
import numpy as np

In [2]:
array_1D=np.array([1,2,3,4,5])

In [3]:
array_1D

array([1, 2, 3, 4, 5])

In [4]:
array_2D=np.random.randint(1,9,size=(3,3))

In [5]:
array_2D

array([[2, 3, 8],
       [6, 4, 1],
       [5, 1, 7]])

In [6]:
arr = np.linspace(0, 5, 10)


In [7]:
arr

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])