In [1]:
import numpy as np

Add 5 to every element in the 1D array.

In [9]:
arr=np.array([1,2,3,4,5])

In [ ]:
arr+5
#OR
np.add(arr,5)

array([ 6,  7,  8,  9, 10])

Multiply the 2D array by 3.



In [2]:
array_2D=np.random.randint(1,9,size=(3,3))

In [4]:
array_2D

array([[4, 2, 6],
       [7, 8, 6],
       [2, 7, 3]])

In [ ]:
array_2D*5
#OR
np.multiply(array_2D,5)

array([[20, 10, 30],
       [35, 40, 30],
       [10, 35, 15]])

Perform matrix multiplication between the following two arrays:


In [6]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

In [ ]:
#For element wise operation

#np.multiply(A,B)


#OR
#For matrix Multiplication
np.matmul(A,B)

array([[19, 22],
       [43, 50]])