In [ ]:
import numpy as np


In [2]:
a=np.random.randint(10,50,size=(5,2,3))

In [3]:
a.shape

(5, 2, 3)

In [4]:
a.ndim

3

In [5]:
a.dtype

dtype('int64')

In [14]:
a.T

array([[[25, 37, 42, 13, 41],
        [22, 28, 22, 46, 41]],

       [[23, 43, 46, 47, 34],
        [40, 17, 20, 41, 40]],

       [[36, 37, 10, 41, 33],
        [22, 26, 32, 20, 39]]])

In [18]:
a.reshape(5,-1)

array([[25, 23, 36, 22, 40, 22],
       [37, 43, 37, 28, 17, 26],
       [42, 46, 10, 22, 20, 32],
       [13, 47, 41, 46, 41, 20],
       [41, 34, 33, 41, 40, 39]])

In [25]:
a.flatten()



array([25, 23, 36, 22, 40, 22, 37, 43, 37, 28, 17, 26, 42, 46, 10, 22, 20,
       32, 13, 47, 41, 46, 41, 20, 41, 34, 33, 41, 40, 39])

In [26]:
a.ravel()

array([25, 23, 36, 22, 40, 22, 37, 43, 37, 28, 17, 26, 42, 46, 10, 22, 20,
       32, 13, 47, 41, 46, 41, 20, 41, 34, 33, 41, 40, 39])

In [27]:
a.sum()

np.int64(964)

In [28]:
a.sum(axis=0)# sum of columns -> vertical sum

array([[158, 193, 157],
       [159, 158, 139]])

In [29]:
a.sum(axis=1)# sum of row -> horizontal sum

array([[47, 63, 58],
       [65, 60, 63],
       [64, 66, 42],
       [59, 88, 61],
       [82, 74, 72]])

In [30]:
a.trace()

array([53, 40, 62])

In [31]:
a.cumsum()

array([ 25,  48,  84, 106, 146, 168, 205, 248, 285, 313, 330, 356, 398,
       444, 454, 476, 496, 528, 541, 588, 629, 675, 716, 736, 777, 811,
       844, 885, 925, 964])

In [32]:
a.cumprod()

array([                  25,                  575,                20700,
                     455400,             18216000,            400752000,
                14827824000,         637596432000,       23591067984000,
            660549903552000,    11229348360384000,   291963057369984000,
       -6184295664170223616, -7776439446187012096, -3977418167031914496,
        4730520693845639168,  2376693508365025280,  2267215972842602496,
       -7419680500465270784,  1763153878613753856, -1497667271674298368,
        4894281797820481536, -2248631100165324800, -8079133855887392768,
         796905235388825600,  8648033929510518784,  8683958568203845632,
        5554163895876190208,   805626950532988928, -5474037076632535040])

In [33]:
a.argmax(axis=0)

array([[2, 3, 3],
       [3, 3, 4]])

In [34]:
a.argmax(axis=1)

array([[0, 1, 0],
       [0, 0, 0],
       [0, 0, 1],
       [1, 0, 0],
       [0, 1, 1]])

In [35]:
a.clip(min=10,max=20)

array([[[20, 20, 20],
        [20, 20, 20]],

       [[20, 20, 20],
        [20, 17, 20]],

       [[20, 20, 10],
        [20, 20, 20]],

       [[13, 20, 20],
        [20, 20, 20]],

       [[20, 20, 20],
        [20, 20, 20]]])

In [40]:
#concatination
arg1=np.random.randint(1,100,size=(3,3))
arg2=np.random.randint(1,100,size=(3,3))

In [41]:
arg1,arg2

(array([[67, 12,  1],
        [12, 48, 56],
        [42, 52, 98]]),
 array([[30, 50, 47],
        [ 5, 52, 96],
        [99, 26, 17]]))

In [ ]:
np.concat([arg1,arg2],axis=1) 

array([[67, 12,  1, 30, 50, 47],
       [12, 48, 56,  5, 52, 96],
       [42, 52, 98, 99, 26, 17]])

In [47]:
np.vstack([arg1,arg2]) #Vstack


array([[67, 12,  1],
       [12, 48, 56],
       [42, 52, 98],
       [30, 50, 47],
       [ 5, 52, 96],
       [99, 26, 17]])

In [46]:
np.hstack([arg1,arg2]) #Hstack

array([[67, 12,  1, 30, 50, 47],
       [12, 48, 56,  5, 52, 96],
       [42, 52, 98, 99, 26, 17]])