In [1]:
import numpy as np


Element wise operations

In [6]:
a=np.array([

    [4,6,8],
    [1,2,4],
])
b=np.random.randint(1,45,size=(2,3))
c=np.linspace((0,5),(60,100),num=7)

In [9]:

np.add(a,b)

array([[29, 18,  9],
       [37, 42, 27]])

In [10]:
np.subtract(a,b)

array([[-21,  -6,   7],
       [-35, -38, -19]])

In [11]:
np.pow(a,2)

array([[16, 36, 64],
       [ 1,  4, 16]])

In [12]:
quo,rem=np.divmod(b,a)


In [15]:
rem

array([[1, 0, 1],
       [0, 0, 3]])

In [14]:
quo

array([[ 6,  2,  0],
       [36, 20,  5]])

Trignometry

In [17]:
np.sin(a)

array([[-0.7568025 , -0.2794155 ,  0.98935825],
       [ 0.84147098,  0.90929743, -0.7568025 ]])

In [ ]:
np.reciprocal(np.tan(b))

array([[-7.48915531, -1.57267341,  0.64209262],
       [ 0.12902442, -0.89508292,  0.62966222]])

In [20]:
np.reciprocal(np.sin(b))

array([[-7.55562355, -1.8636796 ,  1.18839511],
       [-1.00828929,  1.34207803, -1.18172523]])

Matrix Operations

In [24]:
#Transpose
bT=np.transpose(b)

In [27]:
#Matrix Multiplication
res=np.dot(a,bT)

In [30]:
#Trace -> sum of diagonal of a matrix
sum=np.trace(res)
print(sum)

388


In [31]:
#Rank
np.linalg.matrix_rank(a)

np.int64(2)

In [33]:
#Determinant
b=np.random.randint(1,10,size=(3,3))
det_b=np.linalg.det(b)

In [ ]:
#Inverse 
inv=np.linalg.inv(b)


array([[-0.09677419, -0.14516129,  0.27419355],
       [ 0.61290323, -0.08064516, -0.40322581],
       [-0.19354839,  0.20967742,  0.0483871 ]])

solve the equation:
4x+2y=8
5x=3y=9

In [50]:
A=np.array([[4,2],[5,3]])
b=np.array([[8],[9]])


In [51]:
A_inv=np.linalg.inv(A)

In [55]:
X=np.dot(A_inv,b)

In [56]:
X

array([[ 3.],
       [-2.]])

In [52]:
solution = np.linalg.solve(A, b)

In [53]:
solution

array([[ 3.],
       [-2.]])